volumes:
  instance:

services:
  app:
    container_name: "app-idosets"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7010:5000"
    volumes:
      - instance:/main/instance
    restart: always
