volumes:
  instance:

services:
  app:
    container_name: "app-idosets"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4014:5000"
    volumes:
      - instance:/main/instance
    restart: always
