volumes:
  instance:

services:
  app:
    container_name: "idosets"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - instance:/main/app_flask/instance
    restart: always