[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[tool.ruff]
line-length = 80
indent-width = 4
ignore = ["F403", "F405"]

[tool.dev]
npm-binary = "/home/david/.nvm/versions/node/v18.18.2/bin/npm"
vite-dir = "app_vite"
flask-dir = "app_flask"
flask-static-folder = "app_flask/resources/static"
flask-templates-folder = "app_flask/resources/templates"
huey-consumer = "huey_consumer"
huey = "app_flask.huey.run"
