[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[tool.ruff]
line-length = 80
indent-width = 4

[lint]
ignore = ["F403", "F405"]

[tool.pyqwe]
dev = [
    "@async",
    "*:flask run --debug --port 5001",
    "*(frontend):npm run dev",
]

[tool.flask_vite_transporter]
npm_exec = "npm"
npx_exec = "npx"
serve_app = "app"
vite_apps = ["frontend"]