# Flask-Imp Config File
# ------------------------
# Updates the Flask app config with the variables below.
# If any variable below does not exist in the standard Flask env
# vars it is created and will be accessible using
# app.config. All key names defined below will be
# capitalised when imported.
[FLASK]
DEBUG = false
#PROPAGATE_EXCEPTIONS = true
TRAP_HTTP_EXCEPTIONS = false
#TRAP_BAD_REQUEST_ERRORS = true
SECRET_KEY = "<SECRET_KEY>"
SESSION_COOKIE_NAME = "idosets_session"
#SESSION_COOKIE_DOMAIN = "domain-here.com"
#SESSION_COOKIE_PATH = "/"
SESSION_COOKIE_HTTPONLY = true
SESSION_COOKIE_SECURE = false
SESSION_COOKIE_SAMESITE = "Lax"
PERMANENT_SESSION_LIFETIME = 86400  # 24 hours
SESSION_REFRESH_EACH_REQUEST = true
USE_X_SENDFILE = false
#SEND_FILE_MAX_AGE_DEFAULT = 43200
ERROR_404_HELP = false
SERVER_NAME = "<SERVER_NAME>"
APPLICATION_ROOT = "/"
PREFERRED_URL_SCHEME = "<PREFERRED_URL_SCHEME>"
#MAX_CONTENT_LENGTH = 0
#TEMPLATES_AUTO_RELOAD = true
EXPLAIN_TEMPLATE_LOADING = false
MAX_COOKIE_SIZE = 4093

# Environment Specific
RUN_ENV = "<RUN_ENV>"
VITE_URL = "<VITE_URL>"

# Transactional Email
ZEPTO_MAIL_SENDER = "<ZEPTO_MAIL_SENDER>"
ZEPTO_MAIL_API_URL = "<ZEPTO_MAIL_API_URL>"
ZEPTO_MAIL_TOKEN = "<ZEPTO_MAIL_TOKEN>"
EMAIL_SMTP_USERNAME = "<EMAIL_SMTP_USERNAME>"
EMAIL_SMTP_PASSWORD = "<EMAIL_SMTP_PASSWORD>"
EMAIL_SMTP_SERVER = "<EMAIL_SMTP_SERVER>"
EMAIL_SMTP_PORT = "<EMAIL_SMTP_PORT>"

[SESSION]
logged_in = false
account_id = 0
theme = "dark"

[SQLALCHEMY]
SQLALCHEMY_ECHO = false
SQLALCHEMY_TRACK_MODIFICATIONS = false
SQLALCHEMY_RECORD_QUERIES = false

SQLITE_DB_EXTENSION = ".db"
SQLITE_STORE_IN_PARENT = false

[DATABASE.MAIN]
ENABLED = true
DIALECT = "sqlite"
DATABASE_NAME = "database"
LOCATION = ""
