ENABLED = "yes"

[SETTINGS]
URL_PREFIX = "/api"
#SUBDOMAIN = ""
#URL_DEFAULTS = {}
#STATIC_FOLDER = "static"
#TEMPLATE_FOLDER = "templates"
#STATIC_URL_PATH = "/static"
#ROOT_PATH = ""
#CLI_GROUP = ""

[SESSION]
#api_session = "yes"

# Set ENABLED to true to allow the blueprint
# to create a database bind, change settings accordingly.
[DATABASE_BIND]
ENABLED = false
DIALECT = "sqlite"
DATABASE_NAME = "api"
LOCATION = ""
PORT = ""
USERNAME = ""
PASSWORD = ""
