import {createEffect, createSignal, useContext} from "solid-js";
import {useNavigate, useParams} from "@solidjs/router";
import {mainContext} from "../context/mainContext";
import TopMenu from "../components/TopMenu";
import Loading from "../components/Loading";
import Fetcher from "../utilities/fetcher";

export default function Session() {

    const [ctx, setCtx] = useContext(mainContext);
    const navigate = useNavigate();
    const params = useParams();

    const workout_id = params.workout_id
    const workout_session_id = params.workout_session_id

    // workout_session_id is generated by the start workout button on the Workouts page
    const session = new Fetcher(
        {
            workout_id: workout_id,
            workout_session_id: workout_session_id
        },
        ctx.getSession
    )

    const [_session, _setSession] = createSignal({})

    createEffect(() => {
        if (session.data.loading === false) {

        }
    })

    function Page() {
        return (
            <div className={"container"}>
            </div>
        )
    }

    return (
        <>
            <TopMenu/>
            {session.data.loading ? <div className={"pt-10"}><Loading/></div> : <Page/>}
        </>
    );
};
